routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SkillsController;
use App\Http\Controllers\ContactTypeController;
use App\Http\Controllers\TechnologyController;
use App\Http\Controllers\PaymenttypeController;
use App\Http\Controllers\ConsultanttypeController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\StatustypeController;
use App\Http\Controllers\WorktypeController;
use App\Http\Controllers\InterviewtoolsController;
use App\Http\Controllers\CaseworkerController;
use App\Http\Controllers\AccountTypeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\TransactionsController;
use App\Http\Controllers\SMEController;
use App\Http\Controllers\InterviewsController;
use App\Http\Controllers\InstallmentsController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\SMECommentsController;
use App\Http\Controllers\PaymentstatusController;
use App\Http\Controllers\H1BController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\CapController;
use App\Http\Controllers\DailyWorkTrackerController;

use App\Models\logs;

Route::get('test-email', [LoginController::class, 'testEmail']);
Route::get('/login',[LoginController::class, 'show'])->name('login')->middleware('guest');
Route::post('/authenticate',[LoginController::class, 'authenticate'])->name('adminiy.authenticate')->middleware('throttle:4,1');
Route::post('/login',[LoginController::class, 'login'])->name('adminiy.login')->middleware('throttle:4,1');

Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/loginwithotp',[LoginController::class, 'loginwithotp'])->name('loginwithotp');
Route::get('/otpvalidate',[LoginController::class, 'OTPValidate'])->name('otpvalidate');
Route::post('/validateotp',[LoginController::class, 'validateotp'])->name('validateotp');
Route::post('/sendotp',[LoginController::class, 'sendotp']);
 Route::get('/resendotp',[LoginController::class, 'resendotp']);

Route::post('/authenticate_email_with_otp',[LoginController::class, 'authenticateEmailWithOtp'])->name('adminiy.authenticate_email_with_otp');
// Route::get('/login_email_with_otp',[LoginController::class, 'loginEmailWithotp'])->name('loginemailwithotp');
Route::post('/send_email_otp',[LoginController::class, 'sendEmailotp']);
Route::get('/email_otp_validate',[LoginController::class, 'EmailOTPValidate'])->name('emailotpvalidate');
Route::post('/email_validate_otp',[LoginController::class, 'EmailValidateotp'])->name('emailvalidateotp');
Route::get('/resend_email_otp',[LoginController::class, 'resendEmailotp']);

Route::get('/h1b_form',[ContentController::class, 'H1BAppicationForm'])->name('H1BAppicationForm');

Route::post('h1b_save', [ContentController::class, 'H1BSave'])->name('H1BSave');

 //Route::group(['middleware' => ['adminiy', 'permission']], function() {
  Route::middleware('adminiy')->group(function () {
  Route::get('/', function () {return view('index');})->name('adminiy.panel');
  Route::resource('users', UserController::class);
  Route::get('profileupdate', [UserController::class, 'ProfileUpdate'])->name('ProfileUpdate');
  Route::PATCH('adminupdate', [UserController::class, 'adminupdate'])->name('adminupdate');
  Route::get('generalsettings', [UserController::class, 'generalsettings'])->name('generalsettings');
  Route::get('deactivateaccount', [UserController::class, 'deactivateaccount'])->name('deactivateaccount');
  Route::post('logoutalldevices', [UserController::class, 'logoutalldevices'])->name('logoutalldevices');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
  Route::resource('transactions', TransactionsController::class);
  Route::get('details/{id}', [TransactionsController::class, 'details'])->name('details');
  Route::get('installments/{id}', [TransactionsController::class, 'transactiondetails'])->name('transactiondetails');
  Route::get('smes/{id}', [TransactionsController::class, 'smes'])->name('smes');
  Route::get('interviews/{id}', [TransactionsController::class, 'interviews'])->name('interviews');
 
  Route::get('invoice/{id}/{type}', [TransactionsController::class, 'invoice'])->name('invoice');
  Route::resource('comment', CommentsController::class);
  Route::resource('smecomments', SMECommentsController::class);
  Route::resource('contact', ContactController::class);
  Route::get('get_contacts_by_type/{type}', [ContactController::class, 'getContactsByType'])->name('getContactsByType');
  Route::get('smelist', [ContactController::class, 'smelist'])->name('smelist');
  Route::get('contactlist', [ContactController::class, 'contactlist'])->name('contactlist');
  Route::get('notifications', [ContactController::class, 'notifications'])->name('notifications');
  Route::resource('skills', SkillsController::class);
  Route::resource('cap', CapController::class);
  Route::resource('contacttype', ContactTypeController::class);
  Route::resource('sme', SMEController::class);
  Route::post('/search_sme_list', [SMEController::class, 'searchSMEList'])->name('searchSMEList');
   Route::resource('daily_work_track', DailyWorkTrackerController::class);
   Route::group(['prefix'=>'daily_work_track','as'=>'daily_work_track'], function(){
        Route::get('/download_report/{id}', [DailyWorkTrackerController::class, 'download_report'])->name('download_report');
    });
  Route::get('smedetails/{id}', [SMEController::class,'smedetails'])->name('smedetails');
  Route::get('smedetailsview/{id}', [SMEController::class,'smedetailsview'])->name('smedetailsview');
  Route::get('smepayments', [SMEController::class,'smepaymentsdata'])->name('smepaymentsdata');
  Route::post('search_smpayments_list', [SMEController::class,'searchSmpaymentsList'])->name('searchSmpaymentsList');
  Route::resource('interviews', InterviewsController::class);
  Route::post('/search_interview_list', [InterviewsController::class, 'searchInterviewList'])->name('searchInterviewList');
  Route::post('fetchlocation', [LocationController::class, 'fetchlocation'])->name('fetchlocation');
  Route::resource('technology',TechnologyController::class);
  Route::resource('payment_status',PaymentstatusController::class);
  Route::resource('paymenttype',PaymenttypeController::class);
  Route::resource('consultanttype',ConsultanttypeController::class);
  Route::resource('location',LocationController::class);
  Route::resource('states',StatesController::class);
  Route::resource('statustype',StatustypeController::class);
  Route::resource('worktype',WorktypeController::class);
  Route::resource('accounttype',AccountTypeController::class);
  Route::resource('caseworker',CaseworkerController::class);
  Route::resource('interviewtools',InterviewtoolsController::class);
  Route::resource('installment', InstallmentsController::class);
  Route::get('installment/{id}/edit/{type}', [InstallmentsController::class,'edit'])->name('edit');
  Route::get('comments/{id}', [InterviewsController::class, 'comments'])->name('comments');
  Route::get('smecomment/{id}', [SMEController::class, 'smecomments'])->name('smecomments');
  Route::get('dashboard', [UserController::class, 'dashboard'])->name('dashboard');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
  Route::resource('h1b', H1BController::class);
  Route::post('/search_h1b_list', [H1BController::class, 'searchH1B'])->name('searchH1B');
  Route::get('h1bcommunications/{id}',[H1BController::class, 'communications'])->name('communications');
  Route::get('h1bcommunications/{id}/h1bcommentsedit',[H1BController::class, 'h1bcommentsedit'])->name('h1bcommentsedit');
  Route::PATCH('h1bcommunicationsupdate/{id}',[H1BController::class, 'h1bcommunicationsupdate'])->name('h1bcommunicationsupdate');
  Route::post('addh1bdocuments/{id}',[H1BController::class, 'addh1bdocuments'])->name('addh1bdocuments');
  Route::post('addh1bcomments/{id}',[H1BController::class, 'addh1bcomments'])->name('addh1bcomments');
  Route::get('documents/{id}',[H1BController::class, 'documents'])->name('documents');
  Route::get('communications/{id}',[H1BController::class, 'h1bcommunications'])->name('h1bcommunications');
  Route::delete('documentsdestroy/{id}',[H1BController::class, 'documentsdestroy'])->name('documentsdestroy');
  Route::delete('commentsdestroy/{id}',[H1BController::class, 'commentsdestroy'])->name('commentsdestroy');
    #Route::get('userprieviliazes', [UserController::class, 'userprieviliazes'])->name('userprieviliazes');
    Route::get('batchinfo', [UserController::class, 'batchinfo'])->name('batchinfo');
    #Route::get('userprieviliazes', [RolesController::class, 'getRoles'])->name('userprieviliazes');
    Route::resource('roles', RolesController::class);
    
     Route::get('/adminnotifications', function () {

         $countlogs = logs::orderBy('id', 'DESC')->where('contactID',$_GET['id'])->get();
         $logs = logs::orderBy('id', 'DESC')->where('contactID',$_GET['id'])->skip(($_GET['page'] - 1) * $_GET['limit'])
                            ->take($_GET['limit'])->get();
         $count = count($countlogs);
         $total_pages = ceil($count / $_GET['limit']);
         return view('admin_notifications',compact('logs','count','total_pages'));
     });
    /* Batch comments in case worker */
    Route::group(['prefix'=>'case_worker','as'=>'case_worker'], function() {
        Route::group(['prefix'=>'batch_comments','as'=>'batch_comments'], function() {
            Route::get('{batch_id}', [CaseWorkerController::class, 'batchComments'])->name('batchComments');

resources/views/cap.blade.php
@extends('dashboard_layouts.adminmaster')
 @section('content')  
 <div class="card mb-3">
    <div class="card-header">
       
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor">Cap Management</h5>
          
        </div>
        <div class="col-auto ms-auto">
            <div>
                <button class="btn btn-falcon-success btn-sm" data-bs-toggle="modal" data-bs-target="#album-modal" type="button"><span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="ms-1">New</span></button></div>
            </div>
      </div>
  
    </div>
 
    <div class="card-body pt-0">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active" role="tabpanel" aria-labelledby="tab-dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1" id="dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1">
              @if(session('success'))
              <div class="alert alert-success border-2 d-flex align-items-center" role="alert">
              <div class="bg-success me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('success')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              @if(session('failed'))
              <div class="alert alert-danger border-2 d-flex align-items-center" role="alert">
              <div class="bg-danger me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('failed')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              <table class="table table-bordered caps_datatable table-striped fs--1 mb-0" style="width:100%">
                <thead class="bg-200 text-900">
                  <tr>
                    <th >ID</th>
                    <th >Year</th>
                   
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade bd-modal-lg" id="album-modal" tabindex="-1" role="dialog" aria-labelledby="album-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Cap Add </h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
          <form action="{{ route('cap.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            
            <div class="mb-3"><label class="form-label" >Year</label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="year" name="year"  required />
            </div>
           
            <div class="mb-3">
              <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
            </div>
          </form>
         
        </div>
      </div>
    </div>
  </div>
  <div class="modal editmodal fade bd-modal-lg" id="cap-edit-modal" tabindex="-1" role="dialog" aria-labelledby="cap-edit-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Cap Edit</h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
           <div id="cap_edit_data"></div>
        </div>
      </div>
    </div>
  </div>
  
@endsection

resources/views/caseworker.blade.php
@extends('dashboard_layouts.adminmaster')
 @section('content')  
 <div class="card mb-3">
    <div class="card-header">
       
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor">Batch  Management</h5>
          
        </div>
        <div class="col-auto ms-auto">
            <div>
                <button class="btn btn-falcon-success btn-sm" data-bs-toggle="modal" data-bs-target="#album-modal" type="button"><span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="ms-1">New</span></button></div>
            </div>
      </div>
  
    </div>
 
    <div class="card-body pt-0">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active" role="tabpanel" aria-labelledby="tab-dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1" id="dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1">
              @if(session('success'))
              <div class="alert alert-success border-2 d-flex align-items-center" role="alert">
              <div class="bg-success me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('success')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              @if(session('failed'))
              <div class="alert alert-danger border-2 d-flex align-items-center" role="alert">
              <div class="bg-danger me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('failed')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              <table class="table table-bordered caseworker_datatable table-striped fs--1 mb-0" style="width:100%">
                <thead class="bg-200 text-900">
                  <tr>
                    <th >ID</th>
                    <th >Name</th>
                    <th >Participants</th>
                    <th >Is Active</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade bd-modal-lg" id="album-modal" tabindex="-1" role="dialog" aria-labelledby="album-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Create New Batch</h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
          <form action="{{ route('caseworker.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-3"><label class="form-label" >Batch Title </label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="name" name="name"  required />
            </div>
             <div class="row gx-2">
                    <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Batch Start Date</label><span style="color:red"> *</span>
                    <input class="form-control" type="date" id="batch_start_date" name="batch_start_date"  required />
                    </div>
           
                    <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Batch End Date</label><span style="color:red"> *</span>
                    <input class="form-control" type="date" id="batch_end_date" name="batch_end_date"  required />
                    </div>
           
        </div>
        
        
        <div class="row gx-2">
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">SME Name</label><span style="color:red"> *</span>
                     <select class="form-select" aria-label="Default select example" name="consultantName" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($contact)){
                            foreach ($contact as $ckey => $cvalue) { ?>
                                <option value="{{$cvalue->id}}">{{$cvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                </div>
                 <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Technology</label><span style="color:red"> *</span>
                    <select class=" form-select" id="select2insidemodal" style="width:100%" name="technology[]"  data-options='{"removeItemButton":true,"placeholder":true}'  aria-label="Default select example" multiple="multiple" >
                         <option value="">Select Option</option>
                         <?php if(!empty($technology)){
                            foreach ($technology as $tkey => $tvalue) { ?>
                                <option value="{{$tvalue->id}}">{{$tvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
           </div>
           <div class="row gx-2">
            <div class="mb-3 col-md-6"><label class="form-label" >Amount </label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="amount" name="amount"  required />
            </div>
            <div class="mb-3 col-md-6"><label class="form-label" >Participents </label><span style="color:red"> *</span>
              <select class="form-select" name="participants[]" id="select2participents" style="width:100%" data-options='{"removeItemButton":true,"placeholder":true}'  aria-label="Default select example" multiple="multiple">
                  <option value="0">Select participants</option>
                  <?php if ($contacts) { foreach ($contacts as $_c) { ?>
                  <option value="{{ $_c->id }}">{{ $_c->firstname }}</option> 
                  <?php }} ?>
              </select>
            </div>
            </div>
            <div class="row gx-2">
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Created By</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="caseworker" required {{ (Auth::guard('adminiy')->user()->user_id != 5)? 'disabled':'' }}>
                         <option value="">Select Option</option>
                         <?php if(!empty($caseworker)){
                            foreach ($caseworker as $cwkey => $cwvalue) { ?>
                                <option value="{{$cwvalue->id}}" {{ (Auth::guard('adminiy')->user()->user_id == $cwvalue->id)?'selected':'' }}>{{$cwvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                    <?php  if(Auth::guard('adminiy')->user()->user_id != 5){?>
                    <input class="form-control" type="hidden"  name="caseworker" value="{{Auth::guard('adminiy')->user()->user_id}}">
                    <?php } ?>
                </div>
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Assigned To</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="assigned_to" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($caseworker)){
                            foreach ($caseworker as $cwkey => $cwvalue) { ?>
                                <option value="{{$cwvalue->id}}" {{ (Auth::guard('adminiy')->user()->user_id == $cwvalue->id)?'selected':'' }}>{{$cwvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                    <?php  if(Auth::guard('adminiy')->user()->user_id != 5){?>
                    <input class="form-control" type="hidden"  name="assigned_to" value="{{Auth::guard('adminiy')->user()->user_id}}">
                    <?php } ?>
                </div>
            </div>
                
            <div class="form-check"><input class="form-check-input" type="checkbox" checked name="status" />
              <label class="form-label" >Status</label>
            </div>
            <div class="mb-3">
              <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
            </div>
          </form>
         
        </div>
      </div>
    </div>
  </div>
  <div class="modal editmodal fade bd-modal-lg" id="caseworker-edit-modal" tabindex="-1" role="dialog" aria-labelledby="album-edit-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Batch Details Edit</h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
           <div id="edit_data"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal editmodal fade bd-modal-lg" id="caseworker-view-modal" tabindex="-1" role="dialog" aria-labelledby="album-view-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Batch View </h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
        
          <div id="view"></div>
        </div>
      </div>
    </div>
  </div>
  
   <script>

$(document).ready(function() {
   
  $("#select2insidemodal").select2({
    dropdownParent: $("#album-modal")
  });
  
  $("#select2participents").select2({
    dropdownParent: $("#album-modal")
  });
  
  
});

</script>
@endsection

resources/views/consultanttype.blade.php
@extends('dashboard_layouts.adminmaster')
 @section('content')  
 <div class="card mb-3">
    <div class="card-header">
       
      <div class="row flex-between-end">
        <div class="col-auto align-self-center">
          <h5 class="mb-0" data-anchor="data-anchor">Consultant Type Management</h5>
          
        </div>
        <div class="col-auto ms-auto">
            <div>
                <button class="btn btn-falcon-success btn-sm" data-bs-toggle="modal" data-bs-target="#album-modal" type="button"><span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="ms-1">New</span></button></div>
            </div>
      </div>
  
    </div>
 
    <div class="card-body pt-0">
      <div class="tab-content">
        <div class="tab-pane preview-tab-pane active" role="tabpanel" aria-labelledby="tab-dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1" id="dom-c33e079e-6e1a-483b-8755-69c47bcdf1e1">
              @if(session('success'))
              <div class="alert alert-success border-2 d-flex align-items-center" role="alert">
              <div class="bg-success me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('success')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              @if(session('failed'))
              <div class="alert alert-danger border-2 d-flex align-items-center" role="alert">
              <div class="bg-danger me-3 icon-item"><span class="fas fa-check-circle text-white fs-3"></span></div>
              <p class="mb-0 flex-1">{{ session('failed')}}</p><button class="btn-close" type="button" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              @endif
              
             
              
              <table class="table table-bordered consultanttype_datatable table-striped fs--1 mb-0" id="consultanttype_datatable" style="width:100%">
                <thead class="bg-200 text-900">
                  <tr>
                    <th >Id</th>
                    <th >Name</th>
                    <th >Is Active</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody></tbody>
              </table>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade bd-modal-lg" id="album-modal" tabindex="-1" role="dialog" aria-labelledby="album-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Consultant Type Add </h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
          <form action="{{ route('consultanttype.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-3"><label class="form-label" >Consultant Type Name</label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="name" name="name"  required />
            </div>
            
            <div class="form-check"><input class="form-check-input" type="checkbox" checked name="status" />
              <label class="form-label" >Status</label>
            </div>
            <div class="mb-3">
              <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
            </div>
          </form>
         
        </div>
      </div>
    </div>
  </div>
  <div class="modal editmodal fade bd-modal-lg" id="consultanttype-edit-modal" tabindex="-1" role="dialog" aria-labelledby="album-edit-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Consultant Type Edit</h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
           <div id="edit_data"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal editmodal fade bd-modal-lg" id="consultanttype-view-modal" tabindex="-1" role="dialog" aria-labelledby="album-view-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content border-0">
        <div class="modal-header px-5 position-relative modal-shape-header bg-shape">
          <div class="position-relative z-index-1 light">
            <h4 class="mb-0 text-white" id="authentication-modal-label">Consultant Type View </h4>
          </div><button class="btn-close btn-close-white position-absolute top-0 end-0 mt-2 me-2" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body py-4 px-5">
        
          <div id="view"></div>
        </div>
      </div>
    </div>
  </div>
@endsection