routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\SkillsController;
use App\Http\Controllers\ContactTypeController;
use App\Http\Controllers\TechnologyController;
use App\Http\Controllers\PaymenttypeController;
use App\Http\Controllers\ConsultanttypeController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\StatustypeController;
use App\Http\Controllers\WorktypeController;
use App\Http\Controllers\InterviewtoolsController;
use App\Http\Controllers\CaseworkerController;
use App\Http\Controllers\AccountTypeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\TransactionsController;
use App\Http\Controllers\SMEController;
use App\Http\Controllers\InterviewsController;
use App\Http\Controllers\InstallmentsController;
use App\Http\Controllers\CommentsController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\StatesController;
use App\Http\Controllers\SMECommentsController;
use App\Http\Controllers\PaymentstatusController;
use App\Http\Controllers\H1BController;
use App\Http\Controllers\ContentController;
use App\Http\Controllers\CapController;
use App\Http\Controllers\DailyWorkTrackerController;

use App\Models\logs;

Route::get('test-email', [LoginController::class, 'testEmail']);
Route::get('/login',[LoginController::class, 'show'])->name('login')->middleware('guest');
Route::post('/authenticate',[LoginController::class, 'authenticate'])->name('adminiy.authenticate')->middleware('throttle:4,1');
Route::post('/login',[LoginController::class, 'login'])->name('adminiy.login')->middleware('throttle:4,1');

Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/loginwithotp',[LoginController::class, 'loginwithotp'])->name('loginwithotp');
Route::get('/otpvalidate',[LoginController::class, 'OTPValidate'])->name('otpvalidate');
Route::post('/validateotp',[LoginController::class, 'validateotp'])->name('validateotp');
Route::post('/sendotp',[LoginController::class, 'sendotp']);
 Route::get('/resendotp',[LoginController::class, 'resendotp']);

Route::post('/authenticate_email_with_otp',[LoginController::class, 'authenticateEmailWithOtp'])->name('adminiy.authenticate_email_with_otp');
// Route::get('/login_email_with_otp',[LoginController::class, 'loginEmailWithotp'])->name('loginemailwithotp');
Route::post('/send_email_otp',[LoginController::class, 'sendEmailotp']);
Route::get('/email_otp_validate',[LoginController::class, 'EmailOTPValidate'])->name('emailotpvalidate');
Route::post('/email_validate_otp',[LoginController::class, 'EmailValidateotp'])->name('emailvalidateotp');
Route::get('/resend_email_otp',[LoginController::class, 'resendEmailotp']);

Route::get('/h1b_form',[ContentController::class, 'H1BAppicationForm'])->name('H1BAppicationForm');

Route::post('h1b_save', [ContentController::class, 'H1BSave'])->name('H1BSave');

 //Route::group(['middleware' => ['adminiy', 'permission']], function() {
  Route::middleware('adminiy')->group(function () {
  Route::get('/', function () {return view('index');})->name('adminiy.panel');
  Route::resource('users', UserController::class);
  Route::get('profileupdate', [UserController::class, 'ProfileUpdate'])->name('ProfileUpdate');
  Route::PATCH('adminupdate', [UserController::class, 'adminupdate'])->name('adminupdate');
  Route::get('generalsettings', [UserController::class, 'generalsettings'])->name('generalsettings');
  Route::get('deactivateaccount', [UserController::class, 'deactivateaccount'])->name('deactivateaccount');
  Route::post('logoutalldevices', [UserController::class, 'logoutalldevices'])->name('logoutalldevices');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
  Route::resource('transactions', TransactionsController::class);
  Route::get('details/{id}', [TransactionsController::class, 'details'])->name('details');
  Route::get('installments/{id}', [TransactionsController::class, 'transactiondetails'])->name('transactiondetails');
  Route::get('smes/{id}', [TransactionsController::class, 'smes'])->name('smes');
  Route::get('interviews/{id}', [TransactionsController::class, 'interviews'])->name('interviews');
 
  Route::get('invoice/{id}/{type}', [TransactionsController::class, 'invoice'])->name('invoice');
  Route::resource('comment', CommentsController::class);
  Route::resource('smecomments', SMECommentsController::class);
  Route::resource('contact', ContactController::class);
  Route::get('get_contacts_by_type/{type}', [ContactController::class, 'getContactsByType'])->name('getContactsByType');
  Route::get('smelist', [ContactController::class, 'smelist'])->name('smelist');
  Route::get('contactlist', [ContactController::class, 'contactlist'])->name('contactlist');
  Route::get('notifications', [ContactController::class, 'notifications'])->name('notifications');
  Route::resource('skills', SkillsController::class);
  Route::resource('cap', CapController::class);
  Route::resource('contacttype', ContactTypeController::class);
  Route::resource('sme', SMEController::class);
  Route::post('/search_sme_list', [SMEController::class, 'searchSMEList'])->name('searchSMEList');
   Route::resource('daily_work_track', DailyWorkTrackerController::class);
   Route::group(['prefix'=>'daily_work_track','as'=>'daily_work_track'], function(){
        Route::get('/download_report/{id}', [DailyWorkTrackerController::class, 'download_report'])->name('download_report');
    });
  Route::get('smedetails/{id}', [SMEController::class,'smedetails'])->name('smedetails');
  Route::get('smedetailsview/{id}', [SMEController::class,'smedetailsview'])->name('smedetailsview');
  Route::get('smepayments', [SMEController::class,'smepaymentsdata'])->name('smepaymentsdata');
  Route::post('search_smpayments_list', [SMEController::class,'searchSmpaymentsList'])->name('searchSmpaymentsList');
  Route::resource('interviews', InterviewsController::class);
  Route::post('/search_interview_list', [InterviewsController::class, 'searchInterviewList'])->name('searchInterviewList');
  Route::post('fetchlocation', [LocationController::class, 'fetchlocation'])->name('fetchlocation');
  Route::resource('technology',TechnologyController::class);
  Route::resource('payment_status',PaymentstatusController::class);
  Route::resource('paymenttype',PaymenttypeController::class);
  Route::resource('consultanttype',ConsultanttypeController::class);
  Route::resource('location',LocationController::class);
  Route::resource('states',StatesController::class);
  Route::resource('statustype',StatustypeController::class);
  Route::resource('worktype',WorktypeController::class);
  Route::resource('accounttype',AccountTypeController::class);
  Route::resource('caseworker',CaseworkerController::class);
  Route::resource('interviewtools',InterviewtoolsController::class);
  Route::resource('installment', InstallmentsController::class);
  Route::get('installment/{id}/edit/{type}', [InstallmentsController::class,'edit'])->name('edit');
  Route::get('comments/{id}', [InterviewsController::class, 'comments'])->name('comments');
  Route::get('smecomment/{id}', [SMEController::class, 'smecomments'])->name('smecomments');
  Route::get('dashboard', [UserController::class, 'dashboard'])->name('dashboard');
  Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
  Route::resource('h1b', H1BController::class);
  Route::post('/search_h1b_list', [H1BController::class, 'searchH1B'])->name('searchH1B');
  Route::get('h1bcommunications/{id}',[H1BController::class, 'communications'])->name('communications');
  Route::get('h1bcommunications/{id}/h1bcommentsedit',[H1BController::class, 'h1bcommentsedit'])->name('h1bcommentsedit');
  Route::PATCH('h1bcommunicationsupdate/{id}',[H1BController::class, 'h1bcommunicationsupdate'])->name('h1bcommunicationsupdate');
  Route::post('addh1bdocuments/{id}',[H1BController::class, 'addh1bdocuments'])->name('addh1bdocuments');
  Route::post('addh1bcomments/{id}',[H1BController::class, 'addh1bcomments'])->name('addh1bcomments');
  Route::get('documents/{id}',[H1BController::class, 'documents'])->name('documents');
  Route::get('communications/{id}',[H1BController::class, 'h1bcommunications'])->name('h1bcommunications');
  Route::delete('documentsdestroy/{id}',[H1BController::class, 'documentsdestroy'])->name('documentsdestroy');
  Route::delete('commentsdestroy/{id}',[H1BController::class, 'commentsdestroy'])->name('commentsdestroy');
    #Route::get('userprieviliazes', [UserController::class, 'userprieviliazes'])->name('userprieviliazes');
    Route::get('batchinfo', [UserController::class, 'batchinfo'])->name('batchinfo');
    #Route::get('userprieviliazes', [RolesController::class, 'getRoles'])->name('userprieviliazes');
    Route::resource('roles', RolesController::class);
    
     Route::get('/adminnotifications', function () {

         $countlogs = logs::orderBy('id', 'DESC')->where('contactID',$_GET['id'])->get();
         $logs = logs::orderBy('id', 'DESC')->where('contactID',$_GET['id'])->skip(($_GET['page'] - 1) * $_GET['limit'])
                            ->take($_GET['limit'])->get();
         $count = count($countlogs);
         $total_pages = ceil($count / $_GET['limit']);
         return view('admin_notifications',compact('logs','count','total_pages'));
     });
    /* Batch comments in case worker */
    Route::group(['prefix'=>'case_worker','as'=>'case_worker'], function() {
        Route::group(['prefix'=>'batch_comments','as'=>'batch_comments'], function() {
            Route::get('{batch_id}', [CaseWorkerController::class, 'batchComments'])->name('batchComments');

resources/views/modal/Skills_edit.blade.php
<form action="{{ route('skills.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
    <div class="mb-3">
                    <label class="form-label" for="">Technology</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="technology" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($technology)){
                            foreach ($technology as $tkey => $tvalue) { ?>
                                <option value="{{$tvalue->id}}" {{($data->technologyId==$tvalue->id)?'selected':''}}>{{$tvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
      <div class="mb-3"><label class="form-label" >Skill Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
      <div class="mb-3"><label class="form-label" >Roles And Responsibility</label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="rolesres" name="rolesres"  required />
            </div>
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/accounttype_edit.blade.php
<form action="{{ route('accounttype.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
      <div class="mb-3"><label class="form-label" >Account Type Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
     
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/consultanttype_edit.blade.php
<form action="{{ route('consultanttype.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
      <div class="mb-3"><label class="form-label" >Consultant Type Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
     
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/contacttype_edit.blade.php
<form action="{{ route('contacttype.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
      <div class="mb-3"><label class="form-label" >Contact Type Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
     
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/installments_edit.blade.php
<form action="{{ route('installment.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
    <div class="row gx-2">
        <div class="mb-3 col-md-6">
            <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}" required />
                    <label class="form-label" for="">Consultant Name</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="consultantName" disabled>
                         <option value="">Select Option</option>
                         <?php if(!empty($contact)){
                            foreach ($contact as $ckey => $cvalue) { ?>
                                <option value="{{$cvalue->id}}" {{($data->contactId==$cvalue->id)?'selected':''}}>{{$cvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                </div>
        <div class="mb-3 col-sm-6"><label class="form-label" >Date</label><span style="color:red"> *</span>
           
              <input class="form-control" type="date" id="date" name="date" value="{{$data->date}}"  required />
            </div>
     </div>
     <div class="row gx-2">
        <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Technology</label><span style="color:red"> *</span>
                    <select class="form-select organizerMultiple_director" id="organizerMultiple_director" style="width:100%" data-options='{"removeItemButton":true,"placeholder":true}'  aria-label="Default select example" name="technology[]" multiple="multiple" disabled>
                         <option value="">Select Option</option>
                         <?php 
                          $technologies=explode(",", $tras->technology);
                         if(!empty($technology)){
                            foreach ($technology as $tkey => $tvalue) { ?>
                                <option value="{{$tvalue->id}}" <?=(in_array($tvalue->id,$technologies))?'selected':'' ?>>{{$tvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
        <div class="mb-3 col-sm-6"><label class="form-label" >Amount ($)</label><span style="color:red"> *</span>
           
              <input class="form-control" type="text" id="amount" name="amount" value="{{$data->amount}}" readOnly/>
            </div>
     </div>
       <div class="row gx-2">
           
            <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Employee Name</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="caseworker" disabled>
                         <option value="">Select Option</option>
                         <?php if(!empty($caseworker)){
                            foreach ($caseworker as $cwkey => $cwvalue) { ?>
                                <option value="{{$cwvalue->id}}" {{($tras->caseworkerId==$cwvalue->id)?'selected':''}}>{{$cwvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                </div>
                 <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Payment Type</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="paymentType" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($paymenttype)){
                            foreach ($paymenttype as $pkey => $pvalue) { ?>
                                <option value="{{$pvalue->id}}" {{($data->paymentType==$pvalue->id)?'selected':''}}>{{$pvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
               
            </div>
            <div class="row gx-2">
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Payment Status</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="status" id="pstatus" required >
                    <option value="0">Select payment status</option>
                    <?php if ($payment_status) { 
                        foreach ($payment_status as $payment) {
                    ?>
                    <option value="{{ $payment->id }}" {{ ($data->paidStatus == $payment->id) ? 'selected' : '' }}>{{ $payment->name }}</option>
                    <?php } 
                    }
                    ?>
                    </select>
                </div>
                
                 <div class="mb-3 col-md-6 partial">
                    <label class="form-label" for="">Due($)</label><span style="color:red"> *</span>
                    <input type="number" name="due" value="{{$data->due}}" class="form-control">
                </div>
                
                 <div class="mb-3 col-md-6 partial">
                    <label class="form-label" for="">Next Commited Date </label><span style="color:red"> *</span>
                    <input type="date" name="nextcommiteddate" value="{{$data->nextcommiteddate}}" class="form-control">
                </div
                
                <?php if($type == 'sme'){ ?>
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Work Type</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="workType" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($worktype)){
                            foreach ($worktype as $pkey => $pvalue) { ?>
                                <option value="{{$pvalue->id}}"  {{ ($data->type == $pvalue->id) ? 'selected' : '' }}>{{$pvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
                     <?php }else{ ?>
                     <input class="form-control" type="hidden" id="workType" name="workType" value=""/>
                     
                     <?php }?>
            </div>
            <div class="row gx-2">
                <div class="mb-3 col-md-12">
                    <label class="form-label" for="">Comments</label><span style="color:red"> *</span>
                    <textarea class="form-control" rows=5 cols=10 name="comments">{{ $data->comments }}</textarea>
                </div>
            </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>
    <script>

$(document).ready(function() {
    $(".organizerMultiple_director").select2({
    dropdownParent: $("#transactions-edit-modal")
  });
  var status = $('#pstatus').val();
  if(status == 4)
  {
        $('.partial').show();
  }
  else
  {
      $('.partial').hide();
  }
  $('#pstatus').on('change',function(){
       var status = $('#pstatus').val();
      // alert(status);
       if(status == 4)
       {
           $('.partial').show();
       }
       else
       {
           $('.partial').hide();
       }
  })
});

</script>

resources/views/modal/location_edit.blade.php
<form action="{{ route('location.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
    
    <div class="mb-3"><label class="form-label" >Location Code</label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="countryCode" name="countryCode" value="{{$data->countryCode}}"  required />
            </div>
    
      <div class="mb-3"><label class="form-label" >Location Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
     
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/paymenttype_edit.blade.php
<form action="{{ route('paymenttype.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
      <div class="mb-3"><label class="form-label" >Payment Type Name</label><span style="color:red"> *</span>
        <input class="form-control" type="text" id="name" name="name" value="{{$data->name}}"  required />
        <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}"  required />
       
      </div>
     
      <div class="form-check"><input class="form-check-input" type="checkbox" {{ ($data->status==1)?'checked':''}} name="status" />
        <label class="form-label" >Status</label>
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>

resources/views/modal/sme_edit.blade.php
<form action="{{ route('sme.update','1')}}" method="post" enctype="multipart/form-data">
    {{ method_field('PATCH') }}
    @csrf
  
     <div class="row">
            <div class="mb-3 col-md-6"><label class="form-label" >TID</label><span style="color:red"> *</span>
            <input class="form-control" type="hidden" id="id" name="id" value="{{$data->id}}" required />
              <input class="form-control" type="text" id="transactionId" name="transactionId" value="{{$getTransactions->transactionId}}" readonly />
            </div>
              <div class="mb-3 col-md-6"><label class="form-label" >Payment Status</label><span style="color:red"> *</span>
              <select class="form-select" aria-label="Default select example" name="paymentStatus" required>
                    <option value="0">Select payment status</option>
                    <?php if ($payment_statuses) { 
                        foreach ($payment_statuses as $payment) {
                    ?>
                    <option value="{{ $payment->id }}">{{ $payment->name }}</option>
                    <?php } 
                    }
                    ?>
                    </select>
            </div>
            <div class="mb-3 col-md-6"><label class="form-label" >Reason For SME Change</label>
              <input class="form-control" type="text" id="reasonSME" name="reasonSME"  value="{{$data->reasonSME}}"  />
            </div>
            </div>
            
            <div class="row">
            <div class="mb-3 col-md-6"><label class="form-label" >Name Of Consultant</label><span style="color:red"> *</span>
              
               <select class="form-select" aria-label="Default select example" name="contactName" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($contact)){
                            foreach ($contact as $ckey => $cvalue) { ?>
                                <option value="{{$cvalue->id}}" {{($getTransactions->contactId==$cvalue->id)?'selected':''}}>{{$cvalue->firstname}}</option>
                        <?php    }} ?>
                </select>
            </div>
            
            <div class="mb-3 col-md-6"><label class="form-label" >SME Agreed Payment ($)</label><span style="color:red"> *</span>
              <input class="form-control" type="text" id="agreePayment" name="agreePayment" value="{{$data->agreePayment}}" required />
            </div>
            </div>
            
            <div class="row">
             <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Technology</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="technology"  required>
                         <option value="">Select Option</option>
                         
                         <?php 
                         
                         if(!empty($technology)){
                            foreach ($technology as $tkey => $tvalue) { ?>
                                <option value="{{$tvalue->id}}" {{($data->technologyId==$tvalue->id)?'selected':''}}>{{$tvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
            
            
            <div class="mb-3 col-md-6"><label class="form-label" >Comment</label>
              <input class="form-control" type="text" id="name" name="comment" value="{{$data->comment}}"  />
            </div>
            </div>
            
            <div class="row">
            <div class="mb-3 col-md-6"><label class="form-label" >No.of Interviews held</label> 
              <input class="form-control" type="text" id="name" name="NoofInterviews" value="{{$interviews}}"  readOnly/>
            </div>
            
            <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Work Type</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="workType" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($worktype)){
                            foreach ($worktype as $pkey => $pvalue) { ?>
                                <option value="{{$pvalue->id}}" {{($data->workTypeId==$pvalue->id)?'selected':''}}>{{$pvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
            </div>
            
            
            <div class="row">
            <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Resources/Trainer/SME</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="SMEName" required>
                         <option value="">Select Option</option>
                         <?php if(!empty($sme)){
                            foreach ($sme as $ckey => $cvalue) { ?>
                                <option value="{{$cvalue->id}}" {{($data->smeid==$cvalue->id)?'selected':''}}>{{$cvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                </div>
            
           <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Employee</label><span style="color:red"> *</span>
                    <select class="form-select" aria-label="Default select example" name="caseworker" >
                         <option value="">Select Option</option>
                         <?php if(!empty($caseworker)){
                            foreach ($caseworker as $cwkey => $cwvalue) { ?>
                                <option value="{{$cwvalue->id}}" {{($getTransactions->caseworkerId==$cwvalue->id)?'selected':''}}>{{$cwvalue->firstname}}</option>
                        <?php    }} ?>
                    </select>
                    <input class="form-control" type="hidden" id="caseworker" name="caseworker" value={{$getTransactions->caseworkerId}} />
                </div>
                <div class="mb-3 col-md-6">
                    <label class="form-label" for="">Batch</label>
                    <select class="form-select" aria-label="Default select example" name="batch" >
                         <option value="">Select Option</option>
                         <?php if(!empty($batch)){
                            foreach ($batch as $bkey => $bvalue) { ?>
                                <option value="{{$bvalue->id}}" {{($data->batchId==$bvalue->id)?'selected':''}}>{{$bvalue->name}}</option>
                        <?php    }} ?>
                    </select>
                </div>
            
            </div>
      <div class="form-check"><input class="form-check-input" type="hidden" {{ ($data->status==1)?'checked':''}} name="status" />
        
      </div>
      <?php if ($view!=1) { ?>
        <div class="mb-3">
          <button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Submit</button>
        </div>
      <?php } ?>
    </form>